services:
  mysql:
    image: mysql:8.4
    container_name: mysql_ai_schedule
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrongMySqlPassword
      - MYSQL_DATABASE=aischeduleui5
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_ai_schedule
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Vienna
      - TZ=Europe/Vienna
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  mysql-data:
  n8n_data:
